# when changing the version number (here or in package.json), make sure to keep the version|versionName same in both files (JFC)

vars:
  BUNDLE_ID:
    default: com.zaions.invoiceGenerator
  PACKAGE_NAME:
    default: com.zaions.invoiceGenerator
  PRODUCT_NAME:
    default: "Invoice App"
  DISPLAY_NAME:
    default: "Invoice App"

platforms:
  ios:
    targets:
      App:
        bundleId: $BUNDLE_ID
        version: 1.0.0
        buildNumber: 1
        productName: $PRODUCT_NAME
        displayName: $DISPLAY_NAME

  android:
    packageName: $PACKAGE_NAME
    versionName: 1.0.0
    versionCode: 1
